/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.mapletestimony.bill'

type $nsid = typeof $nsid

export { $nsid }

/** A Massachusetts legislature bill mirrored into an ATProto repo. Record key convention: '{court}-{billId}' (e.g. '193-H1234'), which consumers must treat as opaque — court and billId are carried as fields precisely so nothing has to parse the key. Testimony aggregates (counts, latest testimony) belong to an AppView and full document text belongs in blob storage; neither is in the record. */
type Main = {
  $type: 'org.mapletestimony.bill'

  /**
   * General court (legislative session) number, e.g. 193.
   */
  court: number

  /**
   * Bill identifier within the court, e.g. 'H1234'. The upstream API repeats this inside the document as BillNumber; it is carried once, here.
   */
  billId: string
  content: BillContent

  /**
   * Legislative history actions.
   */
  history: HistoryAction[]

  /**
   * Bill ids the legislature reports as similar. Upstream data, not an AppView computation.
   */
  similar?: string[]
  currentCommittee?: Committee

  /**
   * City name, for city council bills.
   */
  city?: string
  topics?: Topic[]

  /**
   * Generated plain-language summary.
   */
  summary?: string

  /**
   * hearingId of each org.mapletestimony.hearing record whose agendas list this bill. Upstream EventIds, deliberately not an AppView's document ids: a consumer joins on the hearing record's own identity and never has to know how MAPLE keys its database.
   */
  hearingIds?: number[]

  /**
   * hearingId of the soonest upcoming hearing. This field, hearingIds and nextHearingAt are joins computed from the hearing records rather than fetched from the legislature; they are in the record because the publisher can compute them and a consumer cannot cheaply.
   */
  nextHearingId?: number
  nextHearingAt?: l.DatetimeString

  /**
   * When this bill was last fetched from the upstream legislature API.
   */
  fetchedAt: l.DatetimeString
}

export type { Main }

/** A Massachusetts legislature bill mirrored into an ATProto repo. Record key convention: '{court}-{billId}' (e.g. '193-H1234'), which consumers must treat as opaque — court and billId are carried as fields precisely so nothing has to parse the key. Testimony aggregates (counts, latest testimony) belong to an AppView and full document text belongs in blob storage; neither is in the record. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    court: /*#__PURE__*/ l.integer(),
    billId: /*#__PURE__*/ l.string({ maxLength: 32 }),
    content: /*#__PURE__*/ l.ref<BillContent>((() => billContent) as any),
    history: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<HistoryAction>((() => historyAction) as any),
    ),
    similar: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ maxLength: 32 })),
    ),
    currentCommittee: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Committee>((() => committee) as any),
    ),
    city: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 128 })),
    topics: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.ref<Topic>((() => topic) as any)),
    ),
    summary: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 10000 }),
    ),
    hearingIds: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.integer()),
    ),
    nextHearingId: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    nextHearingAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    fetchedAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Bill content as published by the legislature, minus what is carried on the record itself (BillNumber, GeneralCourtNumber) and minus DocumentText, which is too large for a record and would be a blob. Only Title and Cosponsors are guaranteed by the upstream API; everything else is optional here because it is nullable or absent there. */
type BillContent = {
  $type?: 'org.mapletestimony.bill#billContent'
  title: string
  docketNumber?: string
  primarySponsor?: MemberReference
  cosponsors: MemberReference[]
  legislationTypeName?: string
  pinslip?: string
}

export type { BillContent }

/** Bill content as published by the legislature, minus what is carried on the record itself (BillNumber, GeneralCourtNumber) and minus DocumentText, which is too large for a record and would be a blob. Only Title and Cosponsors are guaranteed by the upstream API; everything else is optional here because it is nullable or absent there. */
const billContent = /*#__PURE__*/ l.typedObject<BillContent>(
  $nsid,
  'billContent',
  /*#__PURE__*/ l.object({
    title: /*#__PURE__*/ l.string({ maxGraphemes: 2000 }),
    docketNumber: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 32 }),
    ),
    primarySponsor: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<MemberReference>((() => memberReference) as any),
    ),
    cosponsors: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<MemberReference>((() => memberReference) as any),
    ),
    legislationTypeName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 64 }),
    ),
    pinslip: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 2000 }),
    ),
  }),
)

export { billContent }

type MemberReference = {
  $type?: 'org.mapletestimony.bill#memberReference'
  id: string
  name: string

  /**
   * 1 = Legislative Member, 2 = Committee, 3 = Public Request, 4 = Special Request.
   */
  memberType: number
}

export type { MemberReference }

const memberReference = /*#__PURE__*/ l.typedObject<MemberReference>(
  $nsid,
  'memberReference',
  /*#__PURE__*/ l.object({
    id: /*#__PURE__*/ l.string({ maxLength: 32 }),
    name: /*#__PURE__*/ l.string({ maxGraphemes: 256 }),
    memberType: /*#__PURE__*/ l.integer(),
  }),
)

export { memberReference }

type HistoryAction = {
  $type?: 'org.mapletestimony.bill#historyAction'

  /**
   * Upstream legislature date string, preserved verbatim. Not format=datetime: the upstream API emits timestamps without timezone offsets, which ATProto's datetime validation rejects.
   */
  date: string
  branch: string
  action: string
}

export type { HistoryAction }

const historyAction = /*#__PURE__*/ l.typedObject<HistoryAction>(
  $nsid,
  'historyAction',
  /*#__PURE__*/ l.object({
    date: /*#__PURE__*/ l.string({ maxLength: 64 }),
    branch: /*#__PURE__*/ l.string({ maxLength: 64 }),
    action: /*#__PURE__*/ l.string({ maxGraphemes: 2000 }),
  }),
)

export { historyAction }

type Committee = {
  $type?: 'org.mapletestimony.bill#committee'
  id: string
  name: string
  houseChair?: CommitteeMember
  senateChair?: CommitteeMember
}

export type { Committee }

const committee = /*#__PURE__*/ l.typedObject<Committee>(
  $nsid,
  'committee',
  /*#__PURE__*/ l.object({
    id: /*#__PURE__*/ l.string({ maxLength: 32 }),
    name: /*#__PURE__*/ l.string({ maxGraphemes: 256 }),
    houseChair: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<CommitteeMember>((() => committeeMember) as any),
    ),
    senateChair: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<CommitteeMember>((() => committeeMember) as any),
    ),
  }),
)

export { committee }

type CommitteeMember = {
  $type?: 'org.mapletestimony.bill#committeeMember'
  id: string
  name: string
  email?: string
}

export type { CommitteeMember }

const committeeMember = /*#__PURE__*/ l.typedObject<CommitteeMember>(
  $nsid,
  'committeeMember',
  /*#__PURE__*/ l.object({
    id: /*#__PURE__*/ l.string({ maxLength: 32 }),
    name: /*#__PURE__*/ l.string({ maxGraphemes: 256 }),
    email: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 256 })),
  }),
)

export { committeeMember }

type Topic = {
  $type?: 'org.mapletestimony.bill#topic'
  category: string
  topic: string
}

export type { Topic }

const topic = /*#__PURE__*/ l.typedObject<Topic>(
  $nsid,
  'topic',
  /*#__PURE__*/ l.object({
    category: /*#__PURE__*/ l.string({ maxLength: 128 }),
    topic: /*#__PURE__*/ l.string({ maxLength: 128 }),
  }),
)

export { topic }
