/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.mapletestimony.hearing'

type $nsid = typeof $nsid

export { $nsid }

/** A Massachusetts legislature hearing mirrored into an ATProto repo. Record key convention: the upstream EventId as a string (e.g. '4837'), which consumers must treat as opaque — hearingId is carried as a field. Video transcription state (transcript ids, fetch bookkeeping) is our own pipeline's operational state, not legislative data, and is deliberately absent. */
type Main = {
  $type: 'org.mapletestimony.hearing'

  /**
   * Upstream EventId. Unique across general courts.
   */
  hearingId: number
  content: HearingContent

  /**
   * Start instant, resolved from the upstream local date and time in the legislature's time zone. Unlike content.eventDate/startTime this is unambiguous.
   */
  startsAt: l.DatetimeString
  videoUrl?: l.UriString

  /**
   * Names of the hosting committee's chairs, joined from the committee record at scrape time.
   */
  committeeChairs?: string[]

  /**
   * When this hearing was last fetched from the upstream legislature API.
   */
  fetchedAt: l.DatetimeString
}

export type { Main }

/** A Massachusetts legislature hearing mirrored into an ATProto repo. Record key convention: the upstream EventId as a string (e.g. '4837'), which consumers must treat as opaque — hearingId is carried as a field. Video transcription state (transcript ids, fetch bookkeeping) is our own pipeline's operational state, not legislative data, and is deliberately absent. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    hearingId: /*#__PURE__*/ l.integer(),
    content: /*#__PURE__*/ l.ref<HearingContent>((() => hearingContent) as any),
    startsAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    videoUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    committeeChairs: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ maxGraphemes: 256 })),
    ),
    fetchedAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Hearing content as published by the legislature, minus EventId which is carried on the record itself. */
type HearingContent = {
  $type?: 'org.mapletestimony.hearing#hearingContent'

  /**
   * Upstream date string, preserved verbatim. Not format=datetime: the upstream API emits local times with no timezone offset. Use startsAt for an actual instant.
   */
  eventDate: string
  startTime: string
  description: string
  name?: string
  status: string
  host?: HearingHost
  location?: Location
  agendas: Agenda[]
  rescheduledTo?: Reschedule
}

export type { HearingContent }

/** Hearing content as published by the legislature, minus EventId which is carried on the record itself. */
const hearingContent = /*#__PURE__*/ l.typedObject<HearingContent>(
  $nsid,
  'hearingContent',
  /*#__PURE__*/ l.object({
    eventDate: /*#__PURE__*/ l.string({ maxLength: 64 }),
    startTime: /*#__PURE__*/ l.string({ maxLength: 64 }),
    description: /*#__PURE__*/ l.string({ maxGraphemes: 2000 }),
    name: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 512 }),
    ),
    status: /*#__PURE__*/ l.string({ maxLength: 64 }),
    host: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<HearingHost>((() => hearingHost) as any),
    ),
    location: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Location>((() => location) as any),
    ),
    agendas: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<Agenda>((() => agenda) as any),
    ),
    rescheduledTo: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Reschedule>((() => reschedule) as any),
    ),
  }),
)

export { hearingContent }

/** The hosting committee. Both fields are nullable upstream. */
type HearingHost = {
  $type?: 'org.mapletestimony.hearing#hearingHost'
  committeeCode?: string
  generalCourtNumber?: number
}

export type { HearingHost }

/** The hosting committee. Both fields are nullable upstream. */
const hearingHost = /*#__PURE__*/ l.typedObject<HearingHost>(
  $nsid,
  'hearingHost',
  /*#__PURE__*/ l.object({
    committeeCode: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 32 }),
    ),
    generalCourtNumber: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  }),
)

export { hearingHost }

/** Every field is nullable upstream, so none is required here. */
type Location = {
  $type?: 'org.mapletestimony.hearing#location'
  locationName?: string
  addressLine1?: string
  addressLine2?: string
  city?: string
  state?: string
  zipCode?: string
}

export type { Location }

/** Every field is nullable upstream, so none is required here. */
const location = /*#__PURE__*/ l.typedObject<Location>(
  $nsid,
  'location',
  /*#__PURE__*/ l.object({
    locationName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 256 }),
    ),
    addressLine1: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 256 }),
    ),
    addressLine2: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 256 }),
    ),
    city: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 128 }),
    ),
    state: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 64 })),
    zipCode: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 16 }),
    ),
  }),
)

export { location }

type Agenda = {
  $type?: 'org.mapletestimony.hearing#agenda'
  startTime: string
  endTime: string
  topic: string
  documents: AgendaDocument[]
}

export type { Agenda }

const agenda = /*#__PURE__*/ l.typedObject<Agenda>(
  $nsid,
  'agenda',
  /*#__PURE__*/ l.object({
    startTime: /*#__PURE__*/ l.string({ maxLength: 64 }),
    endTime: /*#__PURE__*/ l.string({ maxLength: 64 }),
    topic: /*#__PURE__*/ l.string({ maxGraphemes: 512 }),
    documents: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<AgendaDocument>((() => agendaDocument) as any),
    ),
  }),
)

export { agenda }

/** A bill scheduled at this hearing. billNumber + generalCourtNumber is the ONLY bill<->hearing key the upstream API provides; it is deliberately a plain identifier rather than a strongRef, because the publisher has no CID for the bill record at the time it writes a hearing. */
type AgendaDocument = {
  $type?: 'org.mapletestimony.hearing#agendaDocument'
  billNumber: string
  generalCourtNumber: number
  primarySponsorId?: string
  title: string
}

export type { AgendaDocument }

/** A bill scheduled at this hearing. billNumber + generalCourtNumber is the ONLY bill<->hearing key the upstream API provides; it is deliberately a plain identifier rather than a strongRef, because the publisher has no CID for the bill record at the time it writes a hearing. */
const agendaDocument = /*#__PURE__*/ l.typedObject<AgendaDocument>(
  $nsid,
  'agendaDocument',
  /*#__PURE__*/ l.object({
    billNumber: /*#__PURE__*/ l.string({ maxLength: 32 }),
    generalCourtNumber: /*#__PURE__*/ l.integer(),
    primarySponsorId: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 32 }),
    ),
    title: /*#__PURE__*/ l.string({ maxGraphemes: 2000 }),
  }),
)

export { agendaDocument }

type Reschedule = {
  $type?: 'org.mapletestimony.hearing#reschedule'
  eventDate: string
  startTime: string
}

export type { Reschedule }

const reschedule = /*#__PURE__*/ l.typedObject<Reschedule>(
  $nsid,
  'reschedule',
  /*#__PURE__*/ l.object({
    eventDate: /*#__PURE__*/ l.string({ maxLength: 64 }),
    startTime: /*#__PURE__*/ l.string({ maxLength: 64 }),
  }),
)

export { reschedule }
